# Arquivo de configuração para deploy no Google App Engine que veremos na aula 4

runtime: php55
api_version: 1
version: web
application: treehouse-demo

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /dist
    static_dir: dist
